name: example
description: qlevar_router example project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  qlevar_router:
    path: ../

  url_launcher: ^6.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  #assets: